# CCTV System Configuration
log_level: "debug"

server:
  host: "localhost"
  port: 8080
  signal_port: 8081
  stream_port: 8082
  ssl:
    enabled: false
    cert_file: "certs/cert.pem"
    key_file: "certs/key.pem"

stream:
  video_codec: "h264"
  video_bitrate: 2000
  framerate: 30
  width: 1280
  height: 720
  options:
    preset: "ultrafast"
    tune: "zerolatency"

storage:
  output_dir: "./frames"
  save_frames: true
  max_frames: 1000
  max_disk_usage: 1073741824 # 1GB
  retention_hours: 24
  video_consolidation:
    enabled: True # Make consolidation optional
    interval: "10m" # Consolidation interval when enabled
    min_frames: 300
    delete_originals: false
